show databases;
 use vaishnavi;
  SELECT *FROM STUDENT;
  SELECT NAME, COUNT(*) FROM STUDENT WHERE NAME='KARINA' GROUP BY NAME;
   SELECT ID, COUNT(AGE) AS TOTAL_NAME FROM STUDENT GROUP BY ID HAVING COUNT(AGE)>20;
   SELECT MIN(AGE) AS MINIMUM_AGE FROM STUDENT;
   SELECT MIN(AGE) AS MINIMUM_AGE, MAX(AGE) AS MAXIMUM_AGE FROM STUDENT;
   SELECT MAX(AGE) FROM STUDENT WHERE AGE>20;
   SELECT CURRENT_DATE;
    SELECT CURRENT_TIME;
    SELECT CURRENT_TIMESTAMP;
    SELECT CURDATE();
    SELECT CURTIME();
    SELECT NOW();
    