SHOW DATABASES;
 USE vaishnavi;
 SHOW TABLES;
 SELECT *FROM student;
 SELECT *FROM STUDENT WHERE AGE>20;
  SELECT *FROM STUDENT WHERE AGE>20 AND NAME='KARINA';
  SELECT *FROM STUDENT WHERE AGE>20 OR NAME='KARINA';
  SELECT *FROM STUDENT WHERE NAME IN('MAYURI','SAKSHI','KARINA');
  SELECT *FROM STUDENT WHERE NAME NOT IN('MAYURI','SAKSHI','KARINA');
   SELECT *FROM STUDENT WHERE ID BETWEEN 2 AND 4