show databases;
use vaishnavi;
SELECT *FROM TEACHER;
 SELECT *FROM TEACHER WHERE SPECILIZATION='ROBOTICS';
 SELECT *FROM TEACHER WHERE SPECILIZATION='SCIENCE' AND T_NAME='MOTU';
 SELECT *FROM TEACHER WHERE SPECILIZATION='SCIENCE' OR T_NAME='AKAJA';
 SELECT *FROM TEACHER ORDER BY T_NAME DESC;
 SELECT *FROM TEACHER ORDER BY T_NAME ASC;
 